app = "spleech-rough-wildflower-5228"
primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 5000 # Update this to match Flask's default port
min_machines_running = 1
processes = ["app"]

[experimental]
  auto_rollback = false

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.http_checks]]
    path = "/health"
    interval = "10s"
    timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"


